[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install --legacy-peer-deps',
  'chmod -R +x node_modules/.bin || true'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve dist -s -l $PORT'

