[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

